print ("My name is","Python", end=" ")
print ("Monty Python.",end="\n")
print ("My","name","is","Python","Monty","Python.",sep="-")
print ("     *\n","   * *\n","  *   *\n"," *     *\n","***   ***\n","  *   *\n","  *   *\n","  *****\n")
print ("     *         *\n","   * *       * *\n","  *   *     *   *\n"," *     *   *     *\n","***   *** ***   ***\n","  *   *     *   *\n","  *   *     *   *\n","  *****     *****\n")
print ()
print (0o123)
print (0x123)
