print ("Hello world")
print ()
print ("Itsy bitsy spider\nclimbed the waterspout ")
print ("Down came the rain\nand washed the spider out.")
print ()
print ("Itsy bitsy spider","climbed up","the waterspout")
print ("My name is","Python")
print ("Monty Python.")
print ()
print ("My name is","Python", end=" ")
print ("Monty Python.",end="\n")
print ("My","name","is","Python","Monty","Python.",sep="-")